### PR TITLE
TypeScript defintions

### PR DESCRIPTION
**Pull request by oriSomething**
added support for TypeScript

no need to anything special from the user. in the new version of TS. npm install is enough :)

### CODE REVIEW

**Comment by rwjblue** [comment]
What is required RE: maintenance?

**Comment by oriSomething** [comment]
just update the definition file if needed

**Comment by oriSomething** [comment]
i've made this definition to some tiny experiment i wrote using this library and i would like to create it in TypeScript.
also i saw that glimmer is now in TypeScript, so maybe someone who developed glimmer will have some input about this commit.

**Comment by rwjblue** [comment]
Unless this definition is enforced (I.e. the tests fail when the definition is out of sync) I'm not sure we should land this.

**Comment by oriSomething** [comment]
it's totally your decision. i did this anyway for myself, and i can totally understand if doesn't align with this project needs.
since this project isn't updated very often, it seems to me it's a plus (and it will make my life a bit easier (-;).
but if this addition will be a burden for you. i totally understand if you won't merge this PR.

**Comment by rwjblue** [comment]
It is pretty awesome that you took the time to do this, please don't get me wrong! I am just not an expert TypeScripter so I have no clue what it would take to maintain over time. 

Maybe @wycats / @chancancode / @krisselden have a better understanding.

**Comment by oriSomething** [comment]
NOTE for myself:
[here](https://github.com/oriSomething/simple-html-tokenizer/blob/master/simple-html-tokenizer.d.ts#L8) change to:
```
    attributes?: [string, string, boolean | void][];
```

**Comment by oriSomething** [comment]
i've fixed a few things and added some types. tell me if rebase is needed

**Comment by oriSomething** [comment]
Any new? It seems it won't be ever be merged so I have no idea if I should fix conflicts and updated as needed or just close the PR. Both options are fine with me

**Comment by locks** [comment]
@oriSomething can you rebase? :)

**Comment by locks** [comment]
Sorry @oriSomething, I misspoke! I want to thank you for your work, but we are working on converting the whole project to TypeScript, which would include generating typings when publishing :)
If you want to help with the conversion ping me, I'm trying to figure it out myself 😁

**Comment by oriSomething** [comment]
@locks I would really glad to help, but unfortunately I don't have the time right now, and if an employer doesn't need me to fix something in some OSS project, I barely have the time off work. I wish I could say I'll have a time in a month or two, but you can ask @rwjblue I say for too long 😞

**Pull request closed without merging**
