### PR TITLE
Types

### PR DESCRIPTION
**Pull request by chadhietala**
Would like to get some feedback on this. I wanted to just use the typescript module to do the build however it does not concat UMD builds which lead me down the road of creating CJS and AMD builds.  @chancancode do you know some tricks to get around this issue or is there a preferred output? /cc @rwjblue.

### CODE REVIEW

**Comment by krisselden** [comment]
Did you see this branch? https://github.com/tildeio/simple-html-tokenizer/tree/wip

**Comment by krisselden** [comment]
Also,  look at the build here https://github.com/krisselden/fast-source-map

It supports debugging in vscode with sourcemaps. Targets modules to ES6 but code to ES5 and uses roll up just for modules.

**Comment by chadhietala** [comment]
😞 Didn't see that branch. Probably need to talk to @wycats, I was working on converting Simple DOM and it was relatively quick to turn this into TS.

**Comment by rwjblue** [comment]
Rebased and landed in #42

**Pull request closed without merging**
